"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ZKSound = exports.ZKAttendanceIDMethod = void 0;
var ZKAttendanceIDMethod;
(function (ZKAttendanceIDMethod) {
    ZKAttendanceIDMethod[ZKAttendanceIDMethod["empty"] = 0] = "empty";
    ZKAttendanceIDMethod[ZKAttendanceIDMethod["fingerprint"] = 1] = "fingerprint";
    ZKAttendanceIDMethod[ZKAttendanceIDMethod["face"] = 2] = "face";
    ZKAttendanceIDMethod[ZKAttendanceIDMethod["password"] = 3] = "password";
    ZKAttendanceIDMethod[ZKAttendanceIDMethod["card"] = 4] = "card";
})(ZKAttendanceIDMethod || (exports.ZKAttendanceIDMethod = ZKAttendanceIDMethod = {}));
var ZKSound;
(function (ZKSound) {
    ZKSound[ZKSound["thankYou"] = 0] = "thankYou";
    ZKSound[ZKSound["incorrectPassword"] = 1] = "incorrectPassword";
    ZKSound[ZKSound["accessDenied"] = 2] = "accessDenied";
    ZKSound[ZKSound["invalidID"] = 3] = "invalidID";
    ZKSound[ZKSound["pleaseTryAgain"] = 4] = "pleaseTryAgain";
    ZKSound[ZKSound["duplicateID"] = 5] = "duplicateID";
    ZKSound[ZKSound["theClockIsFlow"] = 6] = "theClockIsFlow";
    ZKSound[ZKSound["theClockIsFull"] = 7] = "theClockIsFull";
    ZKSound[ZKSound["duplicateFinger"] = 8] = "duplicateFinger";
    ZKSound[ZKSound["duplicatedPunch"] = 9] = "duplicatedPunch";
    ZKSound[ZKSound["beepKuko"] = 10] = "beepKuko";
    ZKSound[ZKSound["beepSiren"] = 11] = "beepSiren";
    ZKSound[ZKSound["b12"] = 12] = "b12";
    ZKSound[ZKSound["beepBell"] = 13] = "beepBell";
    ZKSound[ZKSound["b14"] = 14] = "b14";
    ZKSound[ZKSound["b15"] = 15] = "b15";
    ZKSound[ZKSound["b16"] = 16] = "b16";
    ZKSound[ZKSound["b17"] = 17] = "b17";
    ZKSound[ZKSound["openingSound"] = 18] = "openingSound";
    ZKSound[ZKSound["b19"] = 19] = "b19";
    ZKSound[ZKSound["fingerprintNotEmolt"] = 20] = "fingerprintNotEmolt";
    ZKSound[ZKSound["passwordNotEmolt"] = 21] = "passwordNotEmolt";
    ZKSound[ZKSound["badgesNotEmolt"] = 22] = "badgesNotEmolt";
    ZKSound[ZKSound["faceNotEmolt"] = 23] = "faceNotEmolt";
    ZKSound[ZKSound["standard"] = 24] = "standard";
    ZKSound[ZKSound["b25"] = 25] = "b25";
    ZKSound[ZKSound["b26"] = 26] = "b26";
    ZKSound[ZKSound["b27"] = 27] = "b27";
    ZKSound[ZKSound["b28"] = 28] = "b28";
    ZKSound[ZKSound["b29"] = 29] = "b29";
    ZKSound[ZKSound["invalidUser"] = 30] = "invalidUser";
    ZKSound[ZKSound["invalidTimePeriod"] = 31] = "invalidTimePeriod";
    ZKSound[ZKSound["invalidCombination"] = 32] = "invalidCombination";
    ZKSound[ZKSound["illegalAccess"] = 33] = "illegalAccess";
    ZKSound[ZKSound["diskSpaceFull"] = 34] = "diskSpaceFull";
    ZKSound[ZKSound["duplicateFingerprint"] = 35] = "duplicateFingerprint";
    ZKSound[ZKSound["fingerprintNotRegistered"] = 36] = "fingerprintNotRegistered";
    ZKSound[ZKSound["b37"] = 37] = "b37";
    ZKSound[ZKSound["b38"] = 38] = "b38";
    ZKSound[ZKSound["b39"] = 39] = "b39";
    ZKSound[ZKSound["b40"] = 40] = "b40";
    ZKSound[ZKSound["b41"] = 41] = "b41";
    ZKSound[ZKSound["b42"] = 42] = "b42";
    ZKSound[ZKSound["b43"] = 43] = "b43";
    ZKSound[ZKSound["b44"] = 44] = "b44";
    ZKSound[ZKSound["b45"] = 45] = "b45";
    ZKSound[ZKSound["b46"] = 46] = "b46";
    ZKSound[ZKSound["b47"] = 47] = "b47";
    ZKSound[ZKSound["b48"] = 48] = "b48";
    ZKSound[ZKSound["b49"] = 49] = "b49";
    ZKSound[ZKSound["b50"] = 50] = "b50";
    ZKSound[ZKSound["focusEyesOnGreenBox"] = 51] = "focusEyesOnGreenBox";
    ZKSound[ZKSound["b52"] = 52] = "b52";
    ZKSound[ZKSound["b53"] = 53] = "b53";
    ZKSound[ZKSound["b54"] = 54] = "b54";
    ZKSound[ZKSound["b55"] = 55] = "b55";
})(ZKSound || (exports.ZKSound = ZKSound = {}));
//# sourceMappingURL=enums.js.map